# Generated by Django 4.1.2 on 2023-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_blog_author_remove_blog_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='category',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
    ]
