# Generated by Django 4.1.2 on 2023-03-26 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_rename_category_job_experience_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
