# Generated by Django 4.1.2 on 2023-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
