# Generated by Django 4.1.2 on 2023-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('1', 'Applied'), ('2', 'Received, Review Pending'), ('3', 'Review Complete'), ('4', 'Accepted'), ('5', 'Rejected')], default=2, max_length=50),
        ),
    ]
