# Generated by Django 4.1.2 on 2023-03-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[(1, 'Applied'), (2, 'Received'), (3, 'Review Pending'), (4, 'Review Complete'), (5, 'Accepted'), (6, 'Rejected')], default=1, max_length=50),
        ),
    ]
