# Generated by Django 4.1.2 on 2023-03-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_jobapplication_user_alter_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
    ]
