# Generated by Django 4.1.2 on 2023-03-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['applied_on']},
        ),
    ]
