# Generated by Django 4.1.2 on 2023-04-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='provider',
            field=models.CharField(choices=[('1', 'CV'), ('2', 'Linkedin')], default=1, max_length=50),
        ),
    ]
