# Generated by Django 4.1.2 on 2023-04-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_jobapplication_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='provider',
            field=models.CharField(choices=[('1', 'CV'), ('2', 'LinkedIn')], default=1, max_length=50),
        ),
    ]
