# Generated by Django 4.1.2 on 2023-04-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_jobapplication_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='response',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
