# Generated by Django 4.1.2 on 2023-04-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_usersocials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocials',
        ),
    ]
