# Generated by Django 4.1.2 on 2023-03-12 14:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_desc', models.CharField(max_length=2000, null=True)),
                ('author_prof', models.CharField(max_length=100, null=True)),
                ('author_pic', models.ImageField(blank=True, null=True, upload_to='blog/author_pic/')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('stack_overflow', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('blog_desc', models.CharField(default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blog/blog_banners/')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.author')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Name', max_length=250)),
                ('user_email', models.EmailField(blank=True, help_text='E-mail', max_length=300)),
                ('user_pic', django_resized.forms.ResizedImageField(blank=True, crop=None, default='blog/default_pic.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[40, 40], upload_to='blog/user_pic/')),
                ('user_address', models.CharField(default='Unknown', max_length=50)),
                ('body', models.TextField(help_text='Comment', max_length=4000, null=True)),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blog.blog')),
            ],
            options={
                'ordering': ['-commented_on'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
