# Generated by Django 4.1.2 on 2023-04-12 12:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 500], upload_to='blog/blog_banners/'),
        ),
    ]
